version: '3'
services:

  # nginx proxies all http requests to the right service
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8080:8080"

  # frontend service
  frontend:
    image: vm014.qu.tu-berlin.de:6000/csd-frontend-amd64
    volumes:
      - ./configs/frontend-assets/:/app/user-assets/

  # the python backend of the anti-vaxxer bot
  anti-vaxxer-bot-backend:
    image: vm014.qu.tu-berlin.de:6000/anti-vaxxer-bot-python-backend-amd64
    container_name: anti-vaxxer-denier-python-backend
    environment:
      - RASA_NLU_URL=http://anti-vaxxer-nlu:5005/model/parse
      - PRODUCTION=1
    volumes:
      - ./logs/anti-vaxxer-bot/:/app/logs

  # the rasa nlu server of the anti-vaxxer bot
  anti-vaxxer-bot-nlu:
    image: vm014.qu.tu-berlin.de:6000/anti-vaxxer-bot-rasa-nlu-amd64
    container_name: anti-vaxxer-nlu